#use format
# [[services]]
#name = "GitHub"
#url = "https://github.com"
#timeout = 5

[[services]]
name = "GitHub"
url = "https://github.com"
timeout = 5

[[services]]
name = "Discord"
url = "https://discord.com"
timeout = 5

[[services]]
name = "Reddit"
url = "https://www.reddit.com/"
timeout = 5
